# Generated by Django 5.2 on 2025-05-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmcode',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
