# Generated by Django 5.1.7 on 2025-05-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
