# Generated by Django 5.1.7 on 2025-05-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_publications', '0007_postimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
