# Generated by Django 5.1.7 on 2025-05-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_publications', '0008_delete_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(max_length=9, upload_to='images/posts/', verbose_name='Изображение'),
        ),
    ]
